[general]
import = [
    # Themes available in ~/.config/alacritty/themes/
    # "~/.config/alacritty/themes/alacritty_0_12.toml",
     "~/.config/alacritty/themes/alabaster_dark.toml",
    # "~/.config/alacritty/themes/ayu_dark.toml",
    # "~/.config/alacritty/themes/github_dark_colorblind.toml",
]

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Alt"

[font]
size = 12

[font.bold]
family = "UbuntuMono Nerd Font"

[font.italic]
family = "UbuntuMono Nerd Font"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
opacity = 0.95

[window.padding]
x = 2
